### ISSUE TITLE
Is there a version for chrome ?

### ISSUE THREAD

**Issue by xUser5000** [KL13NT/loggy#17]
Is the extension available or will be available for chrome?

**Comment by KL13NT** [comment]
No. I don't plan on building this extension for Chrome. You can fork and work on an update for chrome support, but I don't plan on making it available for chrome in general.

**Comment by mohamedelhefni** [comment]
> Is the extension available or will be available for chrome?

you can use  https://chrome.google.com/webstore/detail/webtime-tracker/ppaojnbmmaigjmlpjaldnkgnklhicppk
